name: Build_and_redeploy_with_N2R

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.ipynb'
      - '**/*.naavrewf'
      - "n2res/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.ipynb'
      - '**/*.naavrewf'
      - "n2res/**"
  workflow_dispatch:

jobs:
  notebook2rest-setup:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout notebook repository
        uses: actions/checkout@v4
        
      - name: Build and Deploy API
        uses: devops-notebook2rest/setup-notebook2rest@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'eu-north-1'
          eks_cluster_name: 'notebook2rest_cluster'
          ecr_repository: 'notebook2rest/api'
